
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 121
#define YY_END_OF_BUFFER 122
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[366] =
    {   0,
        0,    0,  122,  120,    1,    3,  115,    8,  120,   12,
       13,    6,    4,  117,    5,    7,  100,  100,  100,  118,
        2,   10,    9,   11,  116,   75,   79,   77,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,   75,   79,   77,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,    0,  100,  100,    0,  102,  100,  101,  100,
        0,  100,    2,   14,   15,  119,   76,  119,  119,  119,
      101,  119,  119,  119,  119,   16,  119,  119,  119,  119,
      119,   40,   22,   23,  119,  119,  119,  119,   26,   24,

      119,  119,  119,   86,  119,   87,  119,   45,   47,  119,
      119,   52,  119,  119,  119,  119,  119,  119,   92,   93,
       78,  119,  119,  119,   99,  119,   64,   66,  119,  119,
      119,  119,   84,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,   22,  119,
      119,  119,  119,   26,  119,  119,  119,  119,  119,   45,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,   64,   66,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,    0,  113,  101,

      119,   81,   33,  119,  119,   36,   98,  119,  119,   38,
       39,  119,  119,   41,   42,  119,   82,   83,  119,  119,
       31,   17,  119,   44,  119,   46,   48,   49,   50,   51,
      119,  119,   55,   57,   58,   20,   59,    0,    0,   60,
       85,  119,   62,   65,   67,  119,  119,  119,  119,  119,
      119,  119,   96,   97,   94,   95,  119,  119,   72,   74,
      119,  119,  119,  119,  119,  119,  119,   33,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,   55,  119,   62,  119,  119,  119,  119,  119,  119,
      119,  119,  119,   72,  114,    0,  119,   34,   35,  119,

       30,   37,   27,   25,   43,   80,   28,   19,   29,  119,
       54,   56,  104,  106,   61,   63,   91,   90,   68,   69,
       70,   71,   88,   89,  119,   73,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  103,   32,   18,   53,
        0,   21,  119,  119,  119,  119,  119,  119,  105,  119,
      112,  119,  119,  119,  119,  119,  108,  109,  119,  119,
      111,  110,  119,  107,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    6,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    1,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   37,   51,
        1,    1,    1,    1,   52,    1,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   62,   37,   63,   64,   65,
       66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
       37,   76,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[77] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3
    } ;

static const flex_int16_t yy_base[369] =
    {   0,
        0,    0,  797,  798,  798,  798,  798,  798,    0,  798,
      798,  798,  798,  798,  798,  798,   61,  106,   66,  798,
        0,  773,  798,  770,  798,  151,  200,  213,  233,  255,
      276,  307,   56,  102,   68,   58,  753,  749,  301,  271,
      340,   73,  747,   56,  130,  362,  365,  367,  386,  407,
       82,  320,   48,   78,  725,  721,  428,  217,  430,   91,
      719,   58,  781,    0,    0,  489,    0,    0,  798,   72,
      114,  205,    0,  798,  798,  458,  470,  519,  514,    0,
        0,  748,  751,  747,  215,    0,  753,  743,  738,  743,
      749,  538,  551,  564,  577,  731,  738,  262,  746,    0,

      746,  728,  743,    0,  744,    0,  741,  738,    0,  722,
      219,    0,  735,  722,  712,  720,  713,  234,  740,  738,
        0,  704,  694,  697,    0,  694,  705,  702,  683,  687,
      676,  681,    0,  690,  690,  674,   92,  112,  668,  672,
      671,  666,  673,  644,  114,  649,  663,  571,  576,  627,
      628,  620,  338,  624,  614,  609,  613,  613,  594,  606,
      594,  601,  250,  607,  602,  582,  596,  597,  594,  591,
      577,  274,  590,  573,  562,  566,  561,  114,  555,  546,
      549,  547,  561,  559,  540,  545,  538,  539,  547,  546,
      532,  315,  342,  530,  529,  528,  522,  576,  798,  563,

      644,  657,  670,  533,  540,    0,    0,  539,  540,    0,
        0,  537,  523,  683,    0,  513,    0,    0,  518,  528,
        0,    0,  516,    0,  520,    0,    0,    0,    0,    0,
      513,  498,  509,    0,    0,    0,    0,  361,  396,    0,
        0,  503,  501,    0,    0,  502,  491,  502,  486,  494,
      476,  477,    0,    0,    0,    0,  486,  475,  481,    0,
      481,  475,  449,  447,  447,  454,  670,  682,  426,  427,
      423,  424,  420,  406,  398,  404,  412,  403,  400,  395,
      387,  397,  390,  385,  370,  361,  366,  352,  356,  340,
      339,  343,  332,  332,  798,  448,  348,  694,    0,  343,

        0,    0,    0,    0,    0,    0,    0,    0,    0,  343,
        0,    0,  798,  798,    0,    0,    0,    0,    0,    0,
        0,    0,  359,    0,  339,    0,  318,  331,  324,  321,
      292,  300,  270,  254,  248,  248,  798,    0,    0,    0,
      472,    0,  269,  248,  257,  246,  248,  214,  798,  221,
        0,  208,  206,  215,  209,  189,    0,    0,  130,  108,
        0,    0,   40,    0,  798,   81,  765,  767
    } ;

static const flex_int16_t yy_def[369] =
    {   0,
      365,    1,  365,  365,  365,  365,  365,  365,  366,  365,
      365,  365,  365,  365,  365,  365,  365,  365,   17,  365,
      367,  365,  365,  365,  365,  365,   26,   26,   26,   26,
       26,   26,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   26,   26,   46,   46,   46,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,  368,   17,   19,   19,   66,   66,  365,   19,
       66,   66,  367,  365,  365,   46,   46,   26,   26,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   26,   26,   26,   26,   32,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   46,   46,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   46,   46,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,  368,  365,  365,

       26,   26,   26,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   26,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,  365,  365,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   46,   46,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,  365,  365,   32,   46,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,  365,  365,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,  365,   32,   32,   32,
      365,   32,   32,   32,   32,   32,   32,   32,  365,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,    0,  365,  365,  365
    } ;

static const flex_int16_t yy_nxt[875] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,    4,   16,   17,   17,   18,   19,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   32,   33,   34,   32,   35,   36,   37,
       38,   39,   32,   40,   41,   42,   43,   32,   32,   44,
       32,   45,   46,   47,   48,   49,   50,   31,   32,   32,
       51,   52,   53,   54,   55,   56,   57,   32,   58,   59,
       60,   61,   32,   32,   62,   32,   64,   64,   65,   65,
       65,   65,   65,   63,  141,  364,  104,   66,   67,   66,
       68,   66,   66,   66,   69,  105,  113,  106,  115,  142,

      107,  136,  173,  114,  116,  200,  137,  253,  254,  174,
      138,  139,  196,   66,   67,   66,   68,   66,   66,   66,
       69,   70,   70,   70,   70,   70,  197,  255,  256,  108,
      109,  200,   71,   71,   71,   72,   71,   71,  104,   69,
      110,  111,  363,  175,  263,  191,  168,  200,  106,  176,
      192,  169,  112,  193,  194,  264,  143,  144,   71,   71,
       71,   72,   71,   71,  145,   69,   76,   76,   76,   76,
       76,  146,  236,  200,  147,  362,  237,   76,   77,   78,
       79,   76,   76,   80,   81,   80,   82,   80,   83,   80,
       84,   80,   80,   80,   85,   80,   86,   80,   80,   80,

       80,   80,   80,   76,   76,   76,   76,   76,   76,   80,
       81,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   76,   76,   76,
      207,  207,  207,  207,  361,   80,  360,   80,  200,   80,
       76,   76,   76,   80,   87,   80,  228,  229,   88,  359,
       89,  358,   80,  357,   90,  356,   80,   91,   80,   92,
       93,   76,   94,   95,  200,  355,  236,   96,   97,  230,
       80,  237,   80,  182,   98,  354,   80,   99,   80,  183,
      353,  100,   76,   76,   76,  184,  125,  125,  125,  125,
       80,  352,   80,  351,  101,  217,  350,  102,   80,  218,

       80,  126,  103,   76,   76,   76,  342,  219,  127,  217,
      340,   80,  218,   80,  128,   80,  119,  120,  339,   80,
      276,   80,   80,   80,   80,   80,   80,  228,  229,  121,
      253,  254,  338,   80,   80,   80,   80,   80,   80,  348,
       80,  122,   80,  347,   80,  123,   80,  124,  346,  230,
       80,  345,   80,  207,  207,  207,  207,  255,  256,   80,
       80,   80,   80,   80,   80,  344,   80,  129,  130,  343,
      131,  342,  341,  170,  109,  132,  313,  313,  313,  313,
      340,  133,  339,  171,  172,  338,  134,  326,  135,   76,
       76,   76,   76,   76,   76,  112,  336,   80,  324,   80,

       80,   80,   80,  323,   80,   80,  322,   80,   80,  321,
       80,  314,  314,  314,  314,   77,  148,  149,  320,  319,
       76,   76,   76,  150,  151,  318,  152,  317,  155,  156,
      153,   80,   86,  157,  154,   80,  158,   80,   92,  159,
       76,   94,  160,  119,  120,  316,  161,  162,   80,  315,
       80,  312,  163,  311,   80,  164,   80,  335,  309,  100,
       76,   76,   76,  337,  337,  337,  337,  308,   80,   80,
      307,  165,  306,  305,  166,   80,  304,   80,  303,  167,
      302,  301,  121,  185,  186,  334,  187,  349,  349,  349,
      349,  188,  299,  179,  332,  331,  133,  180,  330,  181,

      329,  189,  328,  190,   66,   66,   66,   66,   66,  327,
      326,   76,   76,   76,  325,  324,  323,  322,   66,   80,
       80,  321,   80,   76,   76,   76,   80,  320,   80,  319,
      318,   80,   80,  317,   80,  316,  315,  312,   80,  311,
       80,   76,   76,  203,   66,  201,   76,  202,   76,   80,
      310,   80,  309,   80,   80,  308,   80,   80,   80,   80,
      307,  306,   80,  305,   80,   76,   76,   76,  304,  303,
      302,  301,  300,   80,  299,   80,  296,   80,   76,   76,
       76,   80,  295,   80,  260,  213,   80,  294,   80,  293,
       80,   76,   76,   76,   80,  292,   80,  291,  290,   80,

      289,   80,  288,   80,   76,  214,   76,   80,  287,   80,
      286,  285,   80,  245,   80,  244,   80,  284,  283,  241,
       80,  240,   80,  267,   76,  202,   76,  235,  234,   76,
       76,  268,   80,   80,  282,   80,  281,   80,   80,   80,
       80,   80,  280,  227,   80,  226,   80,   76,   76,   76,
      279,  224,  278,  222,  274,   80,   80,  221,   80,   76,
      214,   76,   80,  277,   80,  275,  215,   80,   80,  273,
       80,   76,   76,   76,   80,  211,   80,  210,  272,   80,
      271,  297,  206,   80,   76,   76,   76,   80,  270,   80,
      269,  266,   80,  265,   80,  262,   80,   76,  298,   76,

       80,  261,   80,  260,  259,   80,  258,   80,  257,   80,
       76,   76,   76,   80,  252,   80,  251,  250,   80,  249,
       80,  248,   80,   76,   76,   76,   80,  247,   80,  246,
      245,   80,  333,  244,   80,   76,  298,   76,   80,  243,
       80,  242,  241,   80,   80,  240,   80,   76,   76,   76,
       80,  239,   80,  238,  235,   80,   80,  234,   80,  233,
      232,  231,   80,  227,   80,   73,  226,   73,   73,  198,
      198,  225,  224,  223,  222,  221,  220,  216,  215,  212,
      211,  210,  209,  208,  206,  205,  204,  199,  195,  178,
      177,  140,  118,  117,   75,   74,  365,    3,  365,  365,

      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365
    } ;

static const flex_int16_t yy_chk[875] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   17,   17,   17,   17,
       17,   19,   19,  366,   44,  363,   33,   17,   17,   17,
       17,   17,   17,   19,   17,   33,   35,   33,   36,   44,

       33,   42,   53,   35,   36,   70,   42,  137,  137,   53,
       42,   42,   62,   17,   17,   17,   17,   17,   17,   19,
       17,   18,   18,   18,   18,   18,   62,  138,  138,   34,
       34,   70,   18,   18,   18,   18,   18,   18,   51,   18,
       34,   34,  360,   54,  145,   60,   51,   71,   51,   54,
       60,   51,   34,   60,   60,  145,   45,   45,   18,   18,
       18,   18,   18,   18,   45,   18,   26,   26,   26,   26,
       26,   45,  178,   71,   45,  359,  178,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,

       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   27,   27,   27,
       85,   85,   85,   85,  356,   27,  355,   27,   72,   27,
       28,   28,   28,   27,   27,   27,  111,  111,   28,  354,
       28,  353,   28,  352,   28,  350,   28,   28,   28,   29,
       29,   29,   29,   29,   72,  348,  118,   29,   29,  111,
       29,  118,   29,   58,   29,  347,   29,   29,   29,   58,
      346,   29,   30,   30,   30,   58,   40,   40,   40,   40,
       30,  345,   30,  344,   30,   98,  343,   30,   30,   98,

       30,   40,   30,   31,   31,   31,  336,   98,   40,  163,
      335,   31,  163,   31,   40,   31,   39,   39,  334,   31,
      163,   31,   32,   32,   32,   32,   32,  172,  172,   39,
      192,  192,  333,   32,   32,   32,   32,   32,   32,  332,
       32,   39,   32,  331,   32,   39,   32,   39,  330,  172,
       32,  329,   32,  153,  153,  153,  153,  193,  193,   32,
       32,   32,   32,   32,   32,  328,   32,   41,   41,  327,
       41,  325,  323,   52,   52,   41,  238,  238,  238,  238,
      310,   41,  300,   52,   52,  297,   41,  294,   41,   46,
       46,   46,   47,   47,   47,   52,  293,   46,  292,   46,

       47,   46,   47,  291,   47,   46,  290,   46,   47,  289,
       47,  239,  239,  239,  239,   46,   46,   46,  288,  287,
       48,   48,   48,   46,   46,  286,   46,  285,   48,   48,
       46,   48,   46,   48,   47,   48,   48,   48,   49,   49,
       49,   49,   49,   57,   57,  284,   49,   49,   49,  283,
       49,  282,   49,  281,   49,   49,   49,  280,  279,   49,
       50,   50,   50,  296,  296,  296,  296,  278,   50,   50,
      277,   50,  276,  275,   50,   50,  274,   50,  273,   50,
      272,  271,   57,   59,   59,  270,   59,  341,  341,  341,
      341,   59,  269,   57,  266,  265,   59,   57,  264,   57,

      263,   59,  262,   59,   66,   66,   66,   66,   66,  261,
      259,   76,   76,   76,  258,  257,  252,  251,   66,   76,
       76,  250,   76,   77,   77,   77,   76,  249,   76,  248,
      247,   77,   77,  246,   77,  243,  242,  233,   77,  232,
       77,   79,   79,   79,   66,   78,   78,   78,   78,   79,
      231,   79,  225,   79,   78,  223,   78,   79,   78,   79,
      220,  219,   78,  216,   78,   92,   92,   92,  213,  212,
      209,  208,  205,   92,  204,   92,  200,   92,   93,   93,
       93,   92,  198,   92,  197,   93,   93,  196,   93,  195,
       93,   94,   94,   94,   93,  194,   93,  191,  190,   94,

      189,   94,  188,   94,   95,   95,   95,   94,  187,   94,
      186,  185,   95,  184,   95,  183,   95,  182,  181,  180,
       95,  179,   95,  148,  148,  148,  148,  177,  176,  149,
      149,  149,  148,  148,  175,  148,  174,  149,  149,  148,
      149,  148,  173,  171,  149,  170,  149,  159,  159,  159,
      169,  168,  167,  166,  159,  159,  159,  165,  159,  160,
      160,  160,  159,  164,  159,  162,  161,  160,  160,  158,
      160,  201,  201,  201,  160,  157,  160,  156,  155,  201,
      154,  201,  152,  201,  202,  202,  202,  201,  151,  201,
      150,  147,  202,  146,  202,  144,  202,  203,  203,  203,

      202,  143,  202,  142,  141,  203,  140,  203,  139,  203,
      214,  214,  214,  203,  136,  203,  135,  134,  214,  132,
      214,  131,  214,  267,  267,  267,  214,  130,  214,  129,
      128,  267,  267,  127,  267,  268,  268,  268,  267,  126,
      267,  124,  123,  268,  268,  122,  268,  298,  298,  298,
      268,  120,  268,  119,  117,  298,  298,  116,  298,  115,
      114,  113,  298,  110,  298,  367,  108,  367,  367,  368,
      368,  107,  105,  103,  102,  101,   99,   97,   96,   91,
       90,   89,   88,   87,   84,   83,   82,   63,   61,   56,
       55,   43,   38,   37,   24,   22,    3,  365,  365,  365,

      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  365,  365
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "globals.h"
#include "symtab.h"
#include "a51.tab.h"

extern int current_line;
#line 765 "lex.yy.c"
/*SYMBOLS*/
/*Registers*/
/*Instructions*/
/*Directives*/
#line 770 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 142 "lex.l"

#line 144 "lex.l"
	/* Comments or Whitespaces */
#line 991 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 366 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 798 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 145 "lex.l"
{/*IGNORE WHITESPACE*/}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 146 "lex.l"
{/*IGNORE LINECOMMENTS*/}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 148 "lex.l"
{current_line+=1;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 150 "lex.l"
{return SUM;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 152 "lex.l"
{return MINUS;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 154 "lex.l"
{return MULTIPLY;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 156 "lex.l"
{return DIVISION;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 158 "lex.l"
{return MODULE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 160 "lex.l"
{return EQ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 162 "lex.l"
{return LT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 164 "lex.l"
{return MT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 166 "lex.l"
{return OP_PAR;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 168 "lex.l"
{return CL_PAR;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 170 "lex.l"
{return SHIFT_L;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 172 "lex.l"
{return SHIFT_R;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 174 "lex.l"
{return AT;}
	YY_BREAK
/*Directives*/
case 17:
YY_RULE_SETUP
#line 177 "lex.l"
{return EQU;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 179 "lex.l"
{return ALIGN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 181 "lex.l"
{return EVEN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 183 "lex.l"
{return ORG;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 185 "lex.l"
{return USING;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 187 "lex.l"
{init_mode = DB_MODE;
		return DB;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 190 "lex.l"
{init_mode = DD_MODE;
		return DD;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 193 "lex.l"
{init_mode = DW_MODE;
		return DW;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 196 "lex.l"
{return DBIT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 198 "lex.l"
{return DS;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 200 "lex.l"
{yylval.segment = CODE_SEGMENT;
		return SEG;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 203 "lex.l"
{yylval.segment = DATA_SEGMENT;
		return SEG;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 206 "lex.l"
{yylval.segment = IDATA_SEGMENT;
		return SEG;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 209 "lex.l"
{yylval.segment = BIT_SEGMENT;
		return SEG;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 212 "lex.l"
{return END;}
	YY_BREAK
/* Instructions */
case 32:
YY_RULE_SETUP
#line 216 "lex.l"
{
	return ACALL;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 219 "lex.l"
{
	return ADD; 
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 222 "lex.l"
{
	return ADDC;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 225 "lex.l"
{
	return AJMP; 
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 228 "lex.l"
{
	return ANL;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 231 "lex.l"
{
	return CJNE;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 234 "lex.l"
{
	return CLR;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 237 "lex.l"
{
	return CPL;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 240 "lex.l"
{
	return DA;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 243 "lex.l"
{
	return DEC;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 246 "lex.l"
{
	return DIV;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 249 "lex.l"
{
	return DJNZ;
}	
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 252 "lex.l"
{
	return INC;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 255 "lex.l"
{
	return JB;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 258 "lex.l"
{
	return JBC;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 261 "lex.l"
{
	return JC;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 264 "lex.l"
{
	return JMP;
}			
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 267 "lex.l"
{
	return JNB;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 270 "lex.l"
{
	return JNC;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 273 "lex.l"
{
	return JNZ;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 276 "lex.l"
{
	return JZ;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 279 "lex.l"
{
	return LCALL;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 282 "lex.l"
{
	return LJMP;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 285 "lex.l"
{
	return MOV;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 288 "lex.l"
{
	return MOVC;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 291 "lex.l"
{
	return MUL;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 294 "lex.l"
{
	return NOP;
}								
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 297 "lex.l"
{
	return ORL;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 300 "lex.l"
{
	return POP;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 303 "lex.l"
{
	return PUSH;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 306 "lex.l"
{
	return RET;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 309 "lex.l"
{
	return RETI;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 312 "lex.l"
{
	return RL;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 315 "lex.l"
{
	return RLC;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 318 "lex.l"
{
	return RR;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 321 "lex.l"
{
	return RRC;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 324 "lex.l"
{
	return SETB;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 327 "lex.l"
{
	return SJMP;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 330 "lex.l"
{
	return SUBB;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 333 "lex.l"
{
	return SWAP;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 336 "lex.l"
{
	return XCH;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 339 "lex.l"
{
	return XCHD;
}							
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 342 "lex.l"
{
	return XRL;
}
	YY_BREAK
/* Compulsory Name Registers*/
case 75:
YY_RULE_SETUP
#line 347 "lex.l"
{ return A; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 348 "lex.l"
{return AB; } 	
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 349 "lex.l"
{ return C; }	
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 350 "lex.l"
{ return PC; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 351 "lex.l"
{ yylval.num = B_REG;
		return B; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 353 "lex.l"
{return DPTR; }
	YY_BREAK
/* SFRs */
case 81:
YY_RULE_SETUP
#line 357 "lex.l"
{ yylval.num = ACC_REG;
		return SFR; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 359 "lex.l"
{ yylval.num = DPH_REG;
		return SFR; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 361 "lex.l"
{ yylval.num = DPL_REG;
		return SFR; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 363 "lex.l"
{ yylval.num = SP_REG;
		return SFR; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 366 "lex.l"
{ yylval.num = PSW_REG;
		return SFR; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 368 "lex.l"
{ yylval.num = IE_REG;
		return SFR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 370 "lex.l"
{ yylval.num = IP_REG;
		return SFR; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 372 "lex.l"
{ yylval.num = TCON_REG;
		return SFR; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 374 "lex.l"
{ yylval.num = TMOD_REG;
		return SFR; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 376 "lex.l"
{ yylval.num = SCON_REG;
		return SFR; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 378 "lex.l"
{ yylval.num = SBUF_REG;
		return SFR; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 381 "lex.l"
{ yylval.num = P0_REG;
		return SFR; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 384 "lex.l"
{ yylval.num = P1_REG;
		 return SFR; }	
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 387 "lex.l"
{ yylval.num = TL0_REG;
		 return SFR; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 390 "lex.l"
{ yylval.num = TL1_REG;
		 return SFR; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 393 "lex.l"
{ yylval.num = TH0_REG;
		 return SFR; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 396 "lex.l"
{ yylval.num = TH1_REG;
		 return SFR; }	
	YY_BREAK
/* Registers */ 
case 98:
YY_RULE_SETUP
#line 401 "lex.l"
{
			yylval.num = atoi(yytext+2);
			return AREG;
			}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 406 "lex.l"
{
				yylval.num = atoi(yytext+1);
				return REG;
			} 		  
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 412 "lex.l"
{
		    char *end;
		    char *numstr = strdup(yytext);
		    
		    /* Remove trailing 'D' or 'd' if present */
		    if (toupper(numstr[strlen(numstr)-1]) == 'D') {
			numstr[strlen(numstr)-1] = '\0';
		    }
		    
		    yylval.num = (int)strtol(numstr, &end, 10);
		    free(numstr);
		    return NUMBER;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 425 "lex.l"
{
   			    char *end;
			    char *numstr = strdup(yytext);
			    
			    /* Remove trailing 'H' or 'h' */
			    if (toupper(numstr[strlen(numstr)-1]) == 'H') {
				numstr[strlen(numstr)-1] = '\0';
			    }
			    
			    yylval.num = (int)strtol(numstr, &end, 16);
			    free(numstr);
			    return NUMBER;
			}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 439 "lex.l"
{
		    	char *end;
		    	char *numstr = strdup(yytext);
		    
		   	 /* Remove trailing 'B' or 'b' */
		   	 	if (toupper(numstr[strlen(numstr)-1]) == 'B') {
				numstr[strlen(numstr)-1] = '\0';
		    	}
		    
		    	/* Convert binary string to integer */
		    	yylval.num = (int)strtol(numstr, &end, 2);
		    	free(numstr);
		    
		    	return NUMBER;}
	YY_BREAK
/* Symbols & Operators */
case 103:
YY_RULE_SETUP
#line 456 "lex.l"
{
	*(yytext+2)='\0';
	yylval.num = (int)((strtol(yytext+1,NULL,16)<<3)+strtol(yytext+4,NULL,10));
	return RAM_BIT_ADDRESS;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 462 "lex.l"
{
	yylval.num = P0_REG + (yytext[3] - '0');
	return SFR_BIT_ADDRESS;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 467 "lex.l"
{
	yylval.num = TCON_REG + (yytext[5] - '0');
	return SFR_BIT_ADDRESS;
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 472 "lex.l"
{
	yylval.num = P1_REG + (yytext[4] - '0');
	return SFR_BIT_ADDRESS;
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 477 "lex.l"
{
	yylval.num = SCON_REG + (yytext[5] - '0');
	return SFR_BIT_ADDRESS;
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 482 "lex.l"
{
	yylval.num = IE_REG + (yytext[3] - '0');
	return SFR_BIT_ADDRESS;
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 487 "lex.l"
{
	yylval.num = IP_REG + (yytext[3] - '0');
	return SFR_BIT_ADDRESS;
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 492 "lex.l"
{
	yylval.num = PSW_REG + (yytext[4] - '0');
	return SFR_BIT_ADDRESS;
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 497 "lex.l"
{
	yylval.num = ACC_REG + (yytext[4] - '0');
	return SFR_BIT_ADDRESS;
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 502 "lex.l"
{
	yylval.num = B_REG + (yytext[2] - '0');
	return SFR_BIT_ADDRESS;
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 507 "lex.l"
{
	yylval.num = *(yytext+1);
	return NUMBER;
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 512 "lex.l"
{
	char* string = (char*)malloc(strlen(yytext) + 1);
	strcpy(string, yytext+1);
	*(string+strlen(string) - 1)='\0';
	yylval.str = string;
	return STRING;
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 521 "lex.l"
{ return HASH_TAG; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 522 "lex.l"
{ return AT_SIGN; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 524 "lex.l"
{ return COMMA; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 526 "lex.l"
{ 
		   return TWO_DOTS; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 529 "lex.l"
{
	yylval.bucket = insertSymbolempty(yytext);
	return IDENTIFIER;
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 534 "lex.l"
{ printf("Unrecognized: %s\n", yytext); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 536 "lex.l"
ECHO;
	YY_BREAK
#line 1857 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 366 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 366 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 365);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 536 "lex.l"



int yywrap(){return 1;}


